-- Store cached semantic embedding vectors for job–candidate matching (generated by AI service).
ALTER TABLE "jobs"
ADD COLUMN "embedding" JSONB,
ADD COLUMN "embedding_updated_at" TIMESTAMP(3);

ALTER TABLE "candidates"
ADD COLUMN "embedding" JSONB,
ADD COLUMN "embedding_updated_at" TIMESTAMP(3);
