#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Deploy Agile Turn ATS to Azure (CLI)
#
# Stack (all-in-one container = Dockerfile stage "render"):
#   - Azure Container Registry
#   - Azure Database for PostgreSQL Flexible Server (pgvector)
#   - Embedded Redis inside the app container (Azure Cache for Redis retired for new creates)
#   - Azure Container Apps (Next.js + AI + Redis + BullMQ worker)
#
# Usage:
#   bash scripts/azure-deploy.sh
#   LOCATION=centralindia RG=ats-rg bash scripts/azure-deploy.sh
#
# Prerequisites: az login, Docker not required (builds in ACR).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Resume prior run if secrets file exists (idempotent re-deploy)
SECRETS_FILE="$ROOT/.azure-deploy.secrets"
if [[ -f "$SECRETS_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a
  # Only load known keys (avoid arbitrary code)
  while IFS='=' read -r k v; do
    case "$k" in
      PG_ADMIN|PG_PASSWORD|NEXTAUTH_SECRET|ACR_NAME|PG_SERVER|REDIS_NAME|APP_NAME|RG|LOCATION|ENV_NAME|PREFIX|\
      SMTP_HOST|SMTP_PORT|SMTP_SECURE|SMTP_USER|SMTP_PASSWORD|SMTP_FROM|EMAIL_SENDING_DOMAIN|EMAIL_SEND_ENABLED|RESEND_API_KEY|\
      GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET)
        [[ -n "${!k:-}" ]] || export "$k=$v"
        ;;
    esac
  done < <(grep -E '^[A-Z_]+=' "$SECRETS_FILE" || true)
  set +a
fi

LOCATION="${LOCATION:-centralindia}"
RG="${RG:-ats-rg}"
PREFIX="${PREFIX:-ats$(date +%y%m%d)}"
# ACR name: alphanumeric only, 5–50 chars, globally unique
ACR_NAME="${ACR_NAME:-${PREFIX}acr}"
ACR_NAME=$(echo "$ACR_NAME" | tr -cd 'a-z0-9' | cut -c1-50)
PG_SERVER="${PG_SERVER:-${PREFIX}-pg}"
REDIS_NAME="${REDIS_NAME:-${PREFIX}-redis}"
ENV_NAME="${ENV_NAME:-${PREFIX}-env}"
APP_NAME="${APP_NAME:-${PREFIX}-app}"
IMAGE_NAME="${IMAGE_NAME:-ats-app}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

PG_ADMIN="${PG_ADMIN:-atsadmin}"
PG_DB="${PG_DB:-atsdb}"
PG_PASSWORD="${PG_PASSWORD:-}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-}"

need() { command -v "$1" >/dev/null || { echo "Missing: $1" >&2; exit 1; }; }
need az
need openssl

echo "════════════════════════════════════════════════════════════"
echo " Azure deploy"
echo "  Location : $LOCATION"
echo "  RG       : $RG"
echo "  ACR      : $ACR_NAME"
echo "  Postgres : $PG_SERVER"
echo "  Redis    : $REDIS_NAME"
echo "  App      : $APP_NAME"
echo "════════════════════════════════════════════════════════════"

STATE=$(az account show --query state -o tsv)
SUB=$(az account show --query name -o tsv)
echo "Subscription: $SUB ($STATE)"
if [[ "$STATE" != "Enabled" ]]; then
  echo "⚠  Subscription state is '$STATE' (not Enabled). Create may fail — check https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade" >&2
fi

if [[ -z "$PG_PASSWORD" ]]; then
  PG_PASSWORD=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24)
fi
if [[ -z "$NEXTAUTH_SECRET" ]]; then
  NEXTAUTH_SECRET=$(openssl rand -base64 32)
fi

# Persist core secrets for re-runs (gitignored). Preserve extra keys (SMTP/Google) already in the file.
CORE_SECRETS_TMP=$(mktemp)
cat > "$CORE_SECRETS_TMP" <<EOF
# Generated by scripts/azure-deploy.sh — do not commit
PREFIX=$PREFIX
PG_ADMIN=$PG_ADMIN
PG_PASSWORD=$PG_PASSWORD
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ACR_NAME=$ACR_NAME
PG_SERVER=$PG_SERVER
REDIS_NAME=$REDIS_NAME
ENV_NAME=$ENV_NAME
APP_NAME=$APP_NAME
RG=$RG
LOCATION=$LOCATION
EOF
if [[ -f "$SECRETS_FILE" ]]; then
  while IFS='=' read -r k v; do
    case "$k" in
      SMTP_HOST|SMTP_PORT|SMTP_SECURE|SMTP_USER|SMTP_PASSWORD|SMTP_FROM|EMAIL_SENDING_DOMAIN|EMAIL_SEND_ENABLED|RESEND_API_KEY|\
      GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET|APP_URL|DATABASE_URL|REDIS_MODE)
        echo "$k=$v" >> "$CORE_SECRETS_TMP"
        ;;
    esac
  done < <(grep -E '^[A-Z_]+=' "$SECRETS_FILE" || true)
fi
# Ensure Google OAuth from env (if set for this run) wins
[[ -n "${GOOGLE_CLIENT_ID:-}" ]] && grep -q '^GOOGLE_CLIENT_ID=' "$CORE_SECRETS_TMP" || true
if [[ -n "${GOOGLE_CLIENT_ID:-}" ]]; then
  grep -v '^GOOGLE_CLIENT_ID=' "$CORE_SECRETS_TMP" > "${CORE_SECRETS_TMP}.2" || true
  mv "${CORE_SECRETS_TMP}.2" "$CORE_SECRETS_TMP"
  echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> "$CORE_SECRETS_TMP"
fi
if [[ -n "${GOOGLE_CLIENT_SECRET:-}" ]]; then
  grep -v '^GOOGLE_CLIENT_SECRET=' "$CORE_SECRETS_TMP" > "${CORE_SECRETS_TMP}.2" || true
  mv "${CORE_SECRETS_TMP}.2" "$CORE_SECRETS_TMP"
  echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> "$CORE_SECRETS_TMP"
fi
mv "$CORE_SECRETS_TMP" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"
echo "Secrets written to $SECRETS_FILE"

echo ""
echo "→ Registering resource providers (no wait)..."
for ns in Microsoft.App Microsoft.ContainerRegistry Microsoft.DBforPostgreSQL Microsoft.Cache Microsoft.OperationalInsights; do
  state=$(az provider show -n "$ns" --query registrationState -o tsv 2>/dev/null || echo "Unknown")
  if [[ "$state" != "Registered" ]]; then
    echo "  registering $ns (was $state)..."
    az provider register --namespace "$ns" -o none || true
  else
    echo "  $ns: Registered"
  fi
done
# Brief settle for providers that just started registering
sleep 3

echo "→ Resource group..."
az group create --name "$RG" --location "$LOCATION" -o none

echo "→ Azure Container Registry (Basic)..."
if ! az acr show -n "$ACR_NAME" -g "$RG" &>/dev/null; then
  az acr create -n "$ACR_NAME" -g "$RG" --sku Basic --admin-enabled true -o none
fi
ACR_LOGIN=$(az acr show -n "$ACR_NAME" -g "$RG" --query loginServer -o tsv)
ACR_USER=$(az acr credential show -n "$ACR_NAME" -g "$RG" --query username -o tsv)
ACR_PASS=$(az acr credential show -n "$ACR_NAME" -g "$RG" --query passwords[0].value -o tsv)

echo "→ PostgreSQL Flexible Server (Burstable B1ms)..."
if ! az postgres flexible-server show -n "$PG_SERVER" -g "$RG" &>/dev/null; then
  az postgres flexible-server create \
    --name "$PG_SERVER" \
    --resource-group "$RG" \
    --location "$LOCATION" \
    --admin-user "$PG_ADMIN" \
    --admin-password "$PG_PASSWORD" \
    --sku-name Standard_B1ms \
    --tier Burstable \
    --storage-size 32 \
    --version 16 \
    --public-access 0.0.0.0-255.255.255.255 \
    --yes \
    -o none
fi

echo "→ Creating database $PG_DB (if missing)..."
az postgres flexible-server db create \
  --resource-group "$RG" \
  --server-name "$PG_SERVER" \
  --database-name "$PG_DB" \
  -o none 2>/dev/null || true

echo "→ Allow Azure services + current IP on Postgres..."
az postgres flexible-server firewall-rule create \
  --resource-group "$RG" \
  --name "$PG_SERVER" \
  --rule-name AllowAzureServices \
  --start-ip-address 0.0.0.0 \
  --end-ip-address 0.0.0.0 \
  -o none 2>/dev/null || true

PG_FQDN=$(az postgres flexible-server show -n "$PG_SERVER" -g "$RG" --query fullyQualifiedDomainName -o tsv)
# Prisma / Node pg: SSL required on Azure
DATABASE_URL="postgresql://${PG_ADMIN}:${PG_PASSWORD}@${PG_FQDN}:5432/${PG_DB}?sslmode=require"

echo "→ Enabling pgvector extension..."
az postgres flexible-server parameter set \
  --resource-group "$RG" \
  --server-name "$PG_SERVER" \
  --name azure.extensions \
  --value VECTOR \
  -o none 2>/dev/null || \
az postgres flexible-server parameter set \
  --resource-group "$RG" \
  --server-name "$PG_SERVER" \
  --name azure.extensions \
  --value vector \
  -o none 2>/dev/null || echo "  (set azure.extensions=VECTOR in portal if this failed)"

# Install extension in DB (may need a short wait after parameter set)
sleep 5
az postgres flexible-server execute \
  --name "$PG_SERVER" \
  --admin-user "$PG_ADMIN" \
  --admin-password "$PG_PASSWORD" \
  --database-name "$PG_DB" \
  --querytext 'CREATE EXTENSION IF NOT EXISTS vector;' \
  2>/dev/null || echo "  Run manually later: CREATE EXTENSION IF NOT EXISTS vector;"

# Classic Azure Cache for Redis is retired for new creates; Azure Managed Redis is costly
# for student plans. The container image starts embedded Redis when REDIS_URL is unset.
echo "→ Redis: embedded in container (REDIS_URL unset → redis-server on 127.0.0.1:6379)"
REDIS_URL=""

echo "→ Log Analytics + Container Apps environment..."
LAW="${PREFIX}-law"
if ! az monitor log-analytics workspace show -n "$LAW" -g "$RG" &>/dev/null; then
  az monitor log-analytics workspace create -n "$LAW" -g "$RG" -l "$LOCATION" -o none
fi
LAW_ID=$(az monitor log-analytics workspace show -n "$LAW" -g "$RG" --query customerId -o tsv)
LAW_KEY=$(az monitor log-analytics workspace get-shared-keys -n "$LAW" -g "$RG" --query primarySharedKey -o tsv)

if ! az containerapp env show -n "$ENV_NAME" -g "$RG" &>/dev/null; then
  az containerapp env create \
    --name "$ENV_NAME" \
    --resource-group "$RG" \
    --location "$LOCATION" \
    --logs-workspace-id "$LAW_ID" \
    --logs-workspace-key "$LAW_KEY" \
    -o none
fi

echo "→ Building image in ACR (Dockerfile target: render) — this takes a long time..."
az acr build \
  --registry "$ACR_NAME" \
  --image "${IMAGE_NAME}:${IMAGE_TAG}" \
  --file Dockerfile \
  --target render \
  "$ROOT"

FULL_IMAGE="${ACR_LOGIN}/${IMAGE_NAME}:${IMAGE_TAG}"

echo "→ Deploying Container App..."
# SMTP: Resend (or other) via secrets file — defaults keep email disabled if unset.
SMTP_HOST="${SMTP_HOST:-}"
SMTP_PORT="${SMTP_PORT:-465}"
SMTP_SECURE="${SMTP_SECURE:-true}"
SMTP_USER="${SMTP_USER:-}"
SMTP_PASSWORD="${SMTP_PASSWORD:-}"
SMTP_FROM="${SMTP_FROM:-}"
EMAIL_SENDING_DOMAIN="${EMAIL_SENDING_DOMAIN:-}"
EMAIL_SEND_ENABLED="${EMAIL_SEND_ENABLED:-0}"

SMTP_ENV_ARGS=()
SECRET_ARGS=("database-url=${DATABASE_URL}" "nextauth-secret=${NEXTAUTH_SECRET}")
if [[ -n "$SMTP_HOST" && -n "$SMTP_FROM" && -n "$SMTP_PASSWORD" ]]; then
  SMTP_ENV_ARGS+=(
    "EMAIL_SEND_ENABLED=${EMAIL_SEND_ENABLED}"
    "SMTP_HOST=${SMTP_HOST}"
    "SMTP_PORT=${SMTP_PORT}"
    "SMTP_SECURE=${SMTP_SECURE}"
    "SMTP_USER=${SMTP_USER:-resend}"
    "SMTP_FROM=${SMTP_FROM}"
    "SMTP_PASSWORD=secretref:smtp-password"
  )
  [[ -n "$EMAIL_SENDING_DOMAIN" ]] && SMTP_ENV_ARGS+=("EMAIL_SENDING_DOMAIN=${EMAIL_SENDING_DOMAIN}")
  SECRET_ARGS+=("smtp-password=${SMTP_PASSWORD}")
  echo "  SMTP: enabled (host=${SMTP_HOST})"
else
  SMTP_ENV_ARGS+=("EMAIL_SEND_ENABLED=0")
  echo "  SMTP: disabled (set SMTP_HOST/SMTP_FROM/SMTP_PASSWORD in .azure-deploy.secrets)"
fi

GOOGLE_ENV_ARGS=()
GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
if [[ -n "$GOOGLE_CLIENT_ID" && -n "$GOOGLE_CLIENT_SECRET" ]]; then
  GOOGLE_ENV_ARGS+=(
    "GOOGLE_CLIENT_ID=secretref:google-client-id"
    "GOOGLE_CLIENT_SECRET=secretref:google-client-secret"
  )
  SECRET_ARGS+=("google-client-id=${GOOGLE_CLIENT_ID}" "google-client-secret=${GOOGLE_CLIENT_SECRET}")
  echo "  Google OAuth: enabled"
else
  echo "  Google OAuth: disabled (set GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET in .azure-deploy.secrets)"
fi

# First create without NEXTAUTH_URL (set after FQDN known), or use placeholder then update
if ! az containerapp show -n "$APP_NAME" -g "$RG" &>/dev/null; then
  az containerapp create \
    --name "$APP_NAME" \
    --resource-group "$RG" \
    --environment "$ENV_NAME" \
    --image "$FULL_IMAGE" \
    --registry-server "$ACR_LOGIN" \
    --registry-username "$ACR_USER" \
    --registry-password "$ACR_PASS" \
    --target-port 3000 \
    --ingress external \
    --cpu 2.0 \
    --memory 4.0Gi \
    --min-replicas 1 \
    --max-replicas 1 \
    --env-vars \
      "NODE_ENV=production" \
      "DATABASE_URL=secretref:database-url" \
      "NEXTAUTH_SECRET=secretref:nextauth-secret" \
      "NEXTAUTH_URL=https://placeholder.local" \
      "AI_SERVICE_URL=http://127.0.0.1:8000" \
      "RESUME_FILES_BASE_PATH=/app/uploads/resumes" \
      "START_WORKER=true" \
      "EMBEDDED_REDIS=true" \
      "${SMTP_ENV_ARGS[@]}" \
      ${GOOGLE_ENV_ARGS[@]+"${GOOGLE_ENV_ARGS[@]}"} \
    --secrets \
      "${SECRET_ARGS[@]}" \
    -o none
else
  az containerapp secret set \
    --name "$APP_NAME" \
    --resource-group "$RG" \
    --secrets \
      "${SECRET_ARGS[@]}" \
    -o none
  az containerapp update \
    --name "$APP_NAME" \
    --resource-group "$RG" \
    --image "$FULL_IMAGE" \
    --cpu 2.0 \
    --memory 4.0Gi \
    --set-env-vars \
      "NODE_ENV=production" \
      "DATABASE_URL=secretref:database-url" \
      "NEXTAUTH_SECRET=secretref:nextauth-secret" \
      "AI_SERVICE_URL=http://127.0.0.1:8000" \
      "RESUME_FILES_BASE_PATH=/app/uploads/resumes" \
      "START_WORKER=true" \
      "EMBEDDED_REDIS=true" \
      "REDIS_URL=" \
      "${SMTP_ENV_ARGS[@]}" \
      ${GOOGLE_ENV_ARGS[@]+"${GOOGLE_ENV_ARGS[@]}"} \
    -o none
fi

FQDN=$(az containerapp show -n "$APP_NAME" -g "$RG" --query properties.configuration.ingress.fqdn -o tsv)
APP_URL="https://${FQDN}"

echo "→ Setting NEXTAUTH_URL=${APP_URL}"
az containerapp update \
  --name "$APP_NAME" \
  --resource-group "$RG" \
  --set-env-vars "NEXTAUTH_URL=${APP_URL}" \
  -o none

{
  echo "APP_URL=$APP_URL"
  echo "DATABASE_URL=$DATABASE_URL"
  echo "REDIS_MODE=embedded"
} >> "$SECRETS_FILE"

echo ""
echo "════════════════════════════════════════════════════════════"
echo " Deploy finished"
echo "  App URL     : $APP_URL"
echo "  Health      : ${APP_URL}/api/health"
echo "  Secrets file: $SECRETS_FILE"
echo ""
echo " First boot can take 3–5 minutes (AI models + migrate)."
echo " If health fails, check logs:"
echo "   az containerapp logs show -n $APP_NAME -g $RG --follow"
echo "════════════════════════════════════════════════════════════"
