#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Deploy Agile Turn ATS to Azure (CLI)
#
# Stack (all-in-one container = Dockerfile stage "render"):
#   - Azure Container Registry
#   - Azure Database for PostgreSQL Flexible Server (pgvector)
#   - Azure Cache for Redis
#   - Azure Container Apps (Next.js + AI service + BullMQ worker)
#
# Usage:
#   bash scripts/azure-deploy.sh
#   LOCATION=centralindia RG=ats-rg bash scripts/azure-deploy.sh
#
# Prerequisites: az login, Docker not required (builds in ACR).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

LOCATION="${LOCATION:-centralindia}"
RG="${RG:-ats-rg}"
PREFIX="${PREFIX:-ats$(date +%y%m%d)}"
# ACR name: alphanumeric only, 5–50 chars, globally unique
ACR_NAME="${ACR_NAME:-${PREFIX}acr}"
ACR_NAME=$(echo "$ACR_NAME" | tr -cd 'a-z0-9' | cut -c1-50)
PG_SERVER="${PG_SERVER:-${PREFIX}-pg}"
REDIS_NAME="${REDIS_NAME:-${PREFIX}-redis}"
ENV_NAME="${ENV_NAME:-${PREFIX}-env}"
APP_NAME="${APP_NAME:-${PREFIX}-app}"
IMAGE_NAME="${IMAGE_NAME:-ats-app}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

PG_ADMIN="${PG_ADMIN:-atsadmin}"
PG_DB="${PG_DB:-atsdb}"
PG_PASSWORD="${PG_PASSWORD:-}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

need() { command -v "$1" >/dev/null || { echo "Missing: $1" >&2; exit 1; }; }
need az
need openssl

echo "════════════════════════════════════════════════════════════"
echo " Azure deploy"
echo "  Location : $LOCATION"
echo "  RG       : $RG"
echo "  ACR      : $ACR_NAME"
echo "  Postgres : $PG_SERVER"
echo "  Redis    : $REDIS_NAME"
echo "  App      : $APP_NAME"
echo "════════════════════════════════════════════════════════════"

STATE=$(az account show --query state -o tsv)
SUB=$(az account show --query name -o tsv)
echo "Subscription: $SUB ($STATE)"
if [[ "$STATE" != "Enabled" ]]; then
  echo "⚠  Subscription state is '$STATE' (not Enabled). Create may fail — check https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade" >&2
fi

if [[ -z "$PG_PASSWORD" ]]; then
  PG_PASSWORD=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24)
fi
if [[ -z "$NEXTAUTH_SECRET" ]]; then
  NEXTAUTH_SECRET=$(openssl rand -base64 32)
fi

# Persist secrets for re-runs / debugging (gitignored via .env*)
SECRETS_FILE="$ROOT/.azure-deploy.secrets"
cat > "$SECRETS_FILE" <<EOF
# Generated by scripts/azure-deploy.sh — do not commit
PG_ADMIN=$PG_ADMIN
PG_PASSWORD=$PG_PASSWORD
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ACR_NAME=$ACR_NAME
PG_SERVER=$PG_SERVER
REDIS_NAME=$REDIS_NAME
APP_NAME=$APP_NAME
RG=$RG
LOCATION=$LOCATION
EOF
chmod 600 "$SECRETS_FILE"
echo "Secrets written to $SECRETS_FILE"

echo ""
echo "→ Registering resource providers..."
for ns in Microsoft.App Microsoft.ContainerRegistry Microsoft.DBforPostgreSQL Microsoft.Cache Microsoft.OperationalInsights; do
  az provider register --namespace "$ns" --wait >/dev/null 2>&1 || az provider register --namespace "$ns" || true
done

echo "→ Resource group..."
az group create --name "$RG" --location "$LOCATION" -o none

echo "→ Azure Container Registry (Basic)..."
if ! az acr show -n "$ACR_NAME" -g "$RG" &>/dev/null; then
  az acr create -n "$ACR_NAME" -g "$RG" --sku Basic --admin-enabled true -o none
fi
ACR_LOGIN=$(az acr show -n "$ACR_NAME" -g "$RG" --query loginServer -o tsv)
ACR_USER=$(az acr credential show -n "$ACR_NAME" -g "$RG" --query username -o tsv)
ACR_PASS=$(az acr credential show -n "$ACR_NAME" -g "$RG" --query passwords[0].value -o tsv)

echo "→ PostgreSQL Flexible Server (Burstable B1ms)..."
if ! az postgres flexible-server show -n "$PG_SERVER" -g "$RG" &>/dev/null; then
  az postgres flexible-server create \
    --name "$PG_SERVER" \
    --resource-group "$RG" \
    --location "$LOCATION" \
    --admin-user "$PG_ADMIN" \
    --admin-password "$PG_PASSWORD" \
    --sku-name Standard_B1ms \
    --tier Burstable \
    --storage-size 32 \
    --version 16 \
    --public-access 0.0.0.0-255.255.255.255 \
    --yes \
    -o none
fi

echo "→ Creating database $PG_DB (if missing)..."
az postgres flexible-server db create \
  --resource-group "$RG" \
  --server-name "$PG_SERVER" \
  --database-name "$PG_DB" \
  -o none 2>/dev/null || true

echo "→ Allow Azure services + current IP on Postgres..."
az postgres flexible-server firewall-rule create \
  --resource-group "$RG" \
  --name "$PG_SERVER" \
  --rule-name AllowAzureServices \
  --start-ip-address 0.0.0.0 \
  --end-ip-address 0.0.0.0 \
  -o none 2>/dev/null || true

PG_FQDN=$(az postgres flexible-server show -n "$PG_SERVER" -g "$RG" --query fullyQualifiedDomainName -o tsv)
# Prisma / Node pg: SSL required on Azure
DATABASE_URL="postgresql://${PG_ADMIN}:${PG_PASSWORD}@${PG_FQDN}:5432/${PG_DB}?sslmode=require"

echo "→ Enabling pgvector extension..."
az postgres flexible-server parameter set \
  --resource-group "$RG" \
  --server-name "$PG_SERVER" \
  --name azure.extensions \
  --value VECTOR \
  -o none 2>/dev/null || \
az postgres flexible-server parameter set \
  --resource-group "$RG" \
  --server-name "$PG_SERVER" \
  --name azure.extensions \
  --value vector \
  -o none 2>/dev/null || echo "  (set azure.extensions=VECTOR in portal if this failed)"

# Install extension in DB (may need a short wait after parameter set)
sleep 5
az postgres flexible-server execute \
  --name "$PG_SERVER" \
  --admin-user "$PG_ADMIN" \
  --admin-password "$PG_PASSWORD" \
  --database-name "$PG_DB" \
  --querytext 'CREATE EXTENSION IF NOT EXISTS vector;' \
  2>/dev/null || echo "  Run manually later: CREATE EXTENSION IF NOT EXISTS vector;"

echo "→ Azure Cache for Redis (Basic C0)..."
if ! az redis show -n "$REDIS_NAME" -g "$RG" &>/dev/null; then
  az redis create \
    --name "$REDIS_NAME" \
    --resource-group "$RG" \
    --location "$LOCATION" \
    --sku Basic \
    --vm-size c0 \
    --enable-non-ssl-port false \
    -o none
  echo "  Waiting for Redis (can take several minutes)..."
  az redis wait --name "$REDIS_NAME" --resource-group "$RG" --created
fi
REDIS_HOST=$(az redis show -n "$REDIS_NAME" -g "$RG" --query hostName -o tsv)
REDIS_KEY=$(az redis list-keys -n "$REDIS_NAME" -g "$RG" --query primaryKey -o tsv)
REDIS_URL="rediss://:${REDIS_KEY}@${REDIS_HOST}:6380"

echo "→ Log Analytics + Container Apps environment..."
LAW="${PREFIX}-law"
if ! az monitor log-analytics workspace show -n "$LAW" -g "$RG" &>/dev/null; then
  az monitor log-analytics workspace create -n "$LAW" -g "$RG" -l "$LOCATION" -o none
fi
LAW_ID=$(az monitor log-analytics workspace show -n "$LAW" -g "$RG" --query customerId -o tsv)
LAW_KEY=$(az monitor log-analytics workspace get-shared-keys -n "$LAW" -g "$RG" --query primarySharedKey -o tsv)

if ! az containerapp env show -n "$ENV_NAME" -g "$RG" &>/dev/null; then
  az containerapp env create \
    --name "$ENV_NAME" \
    --resource-group "$RG" \
    --location "$LOCATION" \
    --logs-workspace-id "$LAW_ID" \
    --logs-workspace-key "$LAW_KEY" \
    -o none
fi

echo "→ Building image in ACR (Dockerfile target: render) — this takes a long time..."
az acr build \
  --registry "$ACR_NAME" \
  --image "${IMAGE_NAME}:${IMAGE_TAG}" \
  --file Dockerfile \
  --target render \
  "$ROOT"

FULL_IMAGE="${ACR_LOGIN}/${IMAGE_NAME}:${IMAGE_TAG}"

echo "→ Deploying Container App..."
# First create without NEXTAUTH_URL (set after FQDN known), or use placeholder then update
if ! az containerapp show -n "$APP_NAME" -g "$RG" &>/dev/null; then
  az containerapp create \
    --name "$APP_NAME" \
    --resource-group "$RG" \
    --environment "$ENV_NAME" \
    --image "$FULL_IMAGE" \
    --registry-server "$ACR_LOGIN" \
    --registry-username "$ACR_USER" \
    --registry-password "$ACR_PASS" \
    --target-port 3000 \
    --ingress external \
    --cpu 2.0 \
    --memory 4.0Gi \
    --min-replicas 1 \
    --max-replicas 1 \
    --env-vars \
      "NODE_ENV=production" \
      "DATABASE_URL=secretref:database-url" \
      "REDIS_URL=secretref:redis-url" \
      "NEXTAUTH_SECRET=secretref:nextauth-secret" \
      "NEXTAUTH_URL=https://placeholder.local" \
      "AI_SERVICE_URL=http://127.0.0.1:8000" \
      "RESUME_FILES_BASE_PATH=/app/uploads/resumes" \
      "START_WORKER=true" \
      "EMAIL_SEND_ENABLED=0" \
    --secrets \
      "database-url=${DATABASE_URL}" \
      "redis-url=${REDIS_URL}" \
      "nextauth-secret=${NEXTAUTH_SECRET}" \
    -o none
else
  az containerapp update \
    --name "$APP_NAME" \
    --resource-group "$RG" \
    --image "$FULL_IMAGE" \
    --cpu 2.0 \
    --memory 4.0Gi \
    --set-env-vars \
      "NODE_ENV=production" \
      "DATABASE_URL=secretref:database-url" \
      "REDIS_URL=secretref:redis-url" \
      "NEXTAUTH_SECRET=secretref:nextauth-secret" \
      "AI_SERVICE_URL=http://127.0.0.1:8000" \
      "RESUME_FILES_BASE_PATH=/app/uploads/resumes" \
      "START_WORKER=true" \
      "EMAIL_SEND_ENABLED=0" \
    -o none
  az containerapp secret set \
    --name "$APP_NAME" \
    --resource-group "$RG" \
    --secrets \
      "database-url=${DATABASE_URL}" \
      "redis-url=${REDIS_URL}" \
      "nextauth-secret=${NEXTAUTH_SECRET}" \
    -o none
fi

FQDN=$(az containerapp show -n "$APP_NAME" -g "$RG" --query properties.configuration.ingress.fqdn -o tsv)
APP_URL="https://${FQDN}"

echo "→ Setting NEXTAUTH_URL=${APP_URL}"
az containerapp update \
  --name "$APP_NAME" \
  --resource-group "$RG" \
  --set-env-vars "NEXTAUTH_URL=${APP_URL}" \
  -o none

{
  echo "APP_URL=$APP_URL"
  echo "DATABASE_URL=$DATABASE_URL"
  echo "REDIS_HOST=$REDIS_HOST"
} >> "$SECRETS_FILE"

echo ""
echo "════════════════════════════════════════════════════════════"
echo " Deploy finished"
echo "  App URL     : $APP_URL"
echo "  Health      : ${APP_URL}/api/health"
echo "  Secrets file: $SECRETS_FILE"
echo ""
echo " First boot can take 3–5 minutes (AI models + migrate)."
echo " If health fails, check logs:"
echo "   az containerapp logs show -n $APP_NAME -g $RG --follow"
echo "════════════════════════════════════════════════════════════"
